### ISSUE TITLE
Named Pipes example is wrong (and doesn't work for me)

### ISSUE THREAD

**Issue by ElvenSpellmaker** [madhuakula/wincmdfu#1]
Hey there, this example shouldn't have the `http://` in it: ![image](https://user-images.githubusercontent.com/2286713/30241846-75f14a4c-9583-11e7-9e83-bb2c2aa52021.png)

Also, it just spouts an error for me:
![image](https://user-images.githubusercontent.com/2286713/30241853-8f00fa82-9583-11e7-9fd9-3193497bb68e.png)

For extra info, here is my version:
![image](https://user-images.githubusercontent.com/2286713/30241875-d8b72d90-9583-11e7-8ff6-8c634d7662db.png)

**Comment by madhuakula** [comment]
Hey @ElvenSpellmaker 

I will check this issue with author, and update you.

Thanks

**Comment by ElvenSpellmaker** [comment]
@madhuakula Hey, did you check this in the end?

**Comment by madhuakula** [comment]
Hey @ElvenSpellmaker 

I have asked author in the Twitter. Hopefully we will get response https://twitter.com/ElvenSpellmaker/status/906554697254928385

My apologies for not getting back on this.

**Comment by riyazwalikar** [comment]
@wincmdfu here

Weird. I just ran the commands again and they work for me, seeing that this was 3 years ago :)

My PS build is 5.1.18362.752. I don't have a system with the same build as yours handy at the moment but I can investigate this and let you know. 

If you can, can you tell me the build number of your PS now?

![one_slash](https://user-images.githubusercontent.com/1900486/82554958-7f2f0e00-9b84-11ea-84d2-ed86c10c5473.png)

![two_slash](https://user-images.githubusercontent.com/1900486/82554961-7fc7a480-9b84-11ea-90aa-e2ec623e29ee.png)


![build_info](https://user-images.githubusercontent.com/1900486/82554951-7e967780-9b84-11ea-9b50-88d1aee7648b.png)
